#! /bin/bash
# VARS
ip_gateway="$(route -n | grep 'UG[ \t]' | awk '{print $2}')"
port="1000" # change port if needed
url_site="http://$ip_gateway:$port"
sleep_secs=1200 # change refresh time if needed
user_name="" # set username
pass_word="" # set password

# LOGIN
magic="$(curl -v --silent $url_site/login? 2>&1 | grep magic | cut -d' ' -f14 | cut -d'"' -f2)"
keep_alive="$(curl -v --silent -d "username=$user_name&password=$pass_word&magic=$magic&4Tredir=$url_site/login?" -X POST $url_site 2>&1 | grep Location | cut -d' ' -f3)"
tput setaf 11; echo "LOGIN"

# LOGOUT TRAP
trap 'curl -s -o /dev/null $url_site/logout? && tput setaf 11; echo -e "\nLOGOUT" && exit' SIGINT
trap 'curl -s -o /dev/null $url_site/logout? && tput setaf 11; echo -e "\nLOGOUT" && exit' TERM

# LOOP
while true
do
	tput setaf 10; echo "$keep_alive"
	tput setaf 10; echo "Refresh every $sleep_secs seconds"
	curl -s -o /dev/null "${keep_alive[@]%$'\r'}"
	ret=$?
	if [ $ret -ne 0 ]; then
		tput setaf 1; echo "LOGIN FAIL"
        	exit 1
	fi
	sleep $sleep_secs
done

